package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/fahid/reclaim/internal/plan"
)

func newInitCmd(f *sharedFlags) *cobra.Command {
	return &cobra.Command{
		Use:   "init",
		Short: "Scaffold a commented .reclaim.yaml from current detections",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			dir, err := os.Getwd()
			if err != nil {
				return err
			}
			outPath := filepath.Join(dir, ".reclaim.yaml")
			if _, err := os.Lstat(outPath); err == nil {
				return exitErrorf(2, ".reclaim.yaml already exists")
			} else if err != nil && !os.IsNotExist(err) {
				return err
			}

			p, err := buildSizedPlan(cmd, []string{dir}, f)
			if err != nil {
				return err
			}

			body := scaffoldControl(p)
			if err := os.WriteFile(outPath, []byte(body), 0o644); err != nil {
				return err
			}
			fmt.Fprintf(cmd.OutOrStdout(), "wrote %s\n", outPath)
			return nil
		},
	}
}

func scaffoldControl(p *plan.Plan) string {
	var b strings.Builder
	b.WriteString("# Generated by `reclaim init`. All keep/delete entries are commented out.\n")
	b.WriteString("# Uncomment to take effect. See spec.md §5 for the full schema.\n")
	b.WriteString("version: 1\n")
	b.WriteString("mode: merge\n")
	b.WriteString("inherit: true\n")
	b.WriteString("\n")

	type entry struct {
		path       string
		reason     string
		regenerate string
	}
	var deletes []entry
	frameworks := map[string]struct{}{}
	seen := map[string]struct{}{}

	for _, d := range p.Decisions {
		if d.Project != nil && d.Project.Framework != "" {
			frameworks[d.Project.Framework] = struct{}{}
		}
		rel := d.Target.RelPath
		if rel == "" {
			rel = filepath.Base(d.Target.Path)
		}
		rel = filepath.ToSlash(rel)
		if _, ok := seen[rel]; ok {
			continue
		}
		seen[rel] = struct{}{}
		deletes = append(deletes, entry{
			path:       rel,
			reason:     d.Target.Reason,
			regenerate: d.Target.Regenerate,
		})
	}
	sort.Slice(deletes, func(i, j int) bool { return deletes[i].path < deletes[j].path })

	b.WriteString("# Hard veto — wins over detectors and delete: below.\n")
	b.WriteString("# keep:\n")
	for _, e := range deletes {
		fmt.Fprintf(&b, "#   - %s\n", e.path)
	}
	b.WriteString("\n")

	b.WriteString("# Additional or explicit deletion candidates.\n")
	b.WriteString("# delete:\n")
	for _, e := range deletes {
		if e.reason != "" || e.regenerate != "" {
			fmt.Fprintf(&b, "#   - path: %s\n", e.path)
			if e.reason != "" {
				fmt.Fprintf(&b, "#     reason: %q\n", e.reason)
			}
			if e.regenerate != "" {
				fmt.Fprintf(&b, "#     regenerate: %q\n", e.regenerate)
			}
		} else {
			fmt.Fprintf(&b, "#   - %s\n", e.path)
		}
	}
	b.WriteString("\n")

	names := make([]string, 0, len(frameworks))
	for f := range frameworks {
		names = append(names, f)
	}
	sort.Strings(names)
	b.WriteString("# Constrain which detectors may run in this subtree.\n")
	b.WriteString("# frameworks:\n")
	if len(names) > 0 {
		b.WriteString("#   only: [")
		b.WriteString(strings.Join(names, ", "))
		b.WriteString("]\n")
	} else {
		b.WriteString("#   only: []\n")
	}
	b.WriteString("#   disable: []\n")
	b.WriteString("\n")
	b.WriteString("# require_git_ignored: true\n")
	b.WriteString("# ignore: false\n")
	return b.String()
}
